version: '2'

services:
  php-env:
      build: ./php
      volumes: 
        - ./php:/var/www/html
      ports:
        - "8081:80"

  mysql-db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    
    environment:
      MYSQL_DATABASE: 'hive'
      MYSQL_ALLOW_EMPTY_PASSWORD: true

  
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8082:80"
    environment:
      - PMA_ARBITRARY=1
