varsion: '3'
services:
  web:
      build: ./php
      ports:
        - "8080:80"
  db:
    image: mysql:5.7
    volumes:
      - ./hive.sql:/docker-entrypoint-initdb.d/hive.sql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hivedb
      MYSQL_USER: hiveuser
      MYSQL_PASSWORD: hivepassword