version: '2'

services:
  php-env:
      build:
        context: ./php
      depends_on:
        - mysql-db
      ports:
        - "8081:80"
      volumes:
        - ./php:/var/www/html 
      restart: always

  mysql-db:
    build:
      context: ./db
    ports:
      - "3306:3306"
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: hive
      MYSQL_ROOT_PASSWORD: root
    restart: always
    command: 
        - --default_authentication_plugin=mysql_native_password
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
    

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8082:80"
    environment:
      - PMA_ARBITRARY=1
